overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-htmlr.yml
targets:
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt
  - MANIFEST.in: MANIFEST.in.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - .travis.yml: travis.yml.jj2
  - .gitignore: gitignore.jj2
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - "docs/source/index.rst": "index.rst.jj2"